sylius_admin_scheduled_command:
    resource: |
        alias: sylius.scheduled_command
        templates: SyliusAdminBundle:Crud
        section: admin
        grid: sylius_admin_scheduled_command
        except: ['show']
        vars:
            index:
                icon: 'box'
    type: sylius.resource

download_schedule_log_file:
    path: /scheduled-commands/download/logfile/{command}
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\DownloadController::downloadLogFile

execute_immediate_schedule:
    path: /scheduled-commands/execute/immediate/{commandId}
    methods: [GET|PUT]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\ScheduledCommandExecuteImmediateController::executeImmediate

sylius_admin_scheduler_empty_log_file:
    path: /scheduled-commands/{command}/clean-log
    methods: [PUT]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Action\CleanLogAction

sylius_admin_scheduler_view_log_file:
    path: /scheduled-commands/{command}/view-log
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\LogViewerController::show
sylius_admin_scheduler_get_log_file:
    path: /scheduled-commands/{command}/get-log.json
    methods: [GET]
    defaults:
        _controller: Synolia\SyliusSchedulerCommandPlugin\Controller\LogViewerController::getLogs
