sylius_grid:
    grids:
        synolia_admin_commands:
            driver:
                options:
                    class: Synolia\SyliusSchedulerCommandPlugin\Entity\Command
            fields:
                name:
                    type: string
                    sortable: ~
                    label: synolia.ui.scheduled_command.name
                command:
                    type: string
                    sortable: ~
                    label: synolia.ui.scheduled_command.command
                cronExpression:
                    type: scheduled_human_readable_expression
                    label: synolia.ui.scheduled_command.cron_expression
                    options:
                       template: '@SynoliaSyliusSchedulerCommandPlugin/Grid/Column/human_readable_expression.html.twig'
                priority:
                    type: string
                    sortable: ~
                    label: synolia.ui.scheduled_command.priority
                enabled:
                    type: twig
                    sortable: ~
                    label: synolia.ui.scheduled_command.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            sorting:
                name: asc
                command: asc
                priority: asc
                enabled: asc
            filters:
                name:
                    label: synolia.ui.scheduled_command.name
                    type: string
                    enabled: true
                command:
                    label: synolia.ui.scheduled_command.command
                    type: string
                    enabled: true
                cronExpression:
                    label: synolia.ui.scheduled_command.cron_expression
                    type: string
                    enabled: true
                priority:
                    label: synolia.ui.scheduled_command.priority
                    type: string
                    enabled: true
                enabled:
                    label: synolia.ui.scheduled_command.enabled
                    type: boolean
                    enabled: true
            actions:
                main:
                    create:
                        type: create
                item:
                    execute:
                        type: schedule_command_execute_immediate
                        label: synolia.ui.scheduled_command.execute_immediate
                        options:
                            link:
                                route: execute_immediate_schedule
                                parameters:
                                    commandId: resource.id
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
        synolia_admin_scheduled_commands:
            driver:
                options:
                    class: Synolia\SyliusSchedulerCommandPlugin\Entity\ScheduledCommand
            fields:
                name:
                    type: string
                    sortable: ~
                    label: synolia.ui.scheduled_command.name
                state:
                    type: scheduled_command_state
                    sortable: ~
                    label: synolia.ui.scheduled_command.state
                    options:
                        template: '@SynoliaSyliusSchedulerCommandPlugin/Grid/Column/scheduled_command_state.html.twig'
                executedAt:
                    type: scheduled_command_executed_at
                    sortable: createdAt
                    label: synolia.ui.scheduled_command.last_execution
                    options:
                        date_format: !php/const \IntlDateFormatter::SHORT
                        time_format: !php/const \IntlDateFormatter::SHORT
                commandExecutionTime:
                    type: scheduled_command_execution_time
                    label: synolia.ui.scheduled_command.command_execution_time
                logFile:
                    type: scheduled_command_url
                    sortable: ~
                    label: synolia.ui.scheduled_command.log_file
                    options:
                        template: '@SynoliaSyliusSchedulerCommandPlugin/Grid/Column/log_file.html.twig'
            sorting:
                executedAt: desc
            filters:
                id:
                    label: synolia.ui.scheduled_command.id
                    type: string
                    enabled: false
                name:
                    label: synolia.ui.scheduled_command.name
                    type: string
                    enabled: true
                command:
                    label: synolia.ui.scheduled_command.command
                    type: string
                    enabled: true
                state:
                    label: synolia.ui.scheduled_command.state
                    type: string
                    enabled: true
            actions:
                main:
                    create:
                        type: create
                        label: synolia.ui.launch_a_command
                item:
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
    templates:
        action:
            schedule_command_execute_immediate: "@SynoliaSyliusSchedulerCommandPlugin/Grid/Action/execute_immediate.html.twig"
            link: "@SynoliaSyliusSchedulerCommandPlugin/Grid/Action/link.html.twig"
